version: 2

sources:
  - name: raw
    description: "Raw data ingested from Landing Zone (Bronze Layer)"
    schema: main
    tables:
      - name: itviec_jobs
        identifier: raw_itviec_jobs
        description: "Raw ITviec job postings"
        columns:
          - name: job_id
            tests:
              - not_null

      - name: topcv_jobs
        identifier: raw_topcv_jobs
        description: "Raw TopCV job postings"
        columns:
          - name: job_id
            tests:
              - not_null

  # Khai báo tầng Silver để hàn gắn Data Lineage
  - name: silver
    description: "Standardized and AI-enriched job data"
    schema: main
    tables:
      - name: all_jobs
        identifier: silver_all_jobs
        description: "Silver layer containing enriched tech stack, roles, and levels"
        columns:
          - name: job_id
            tests:
              - unique
              - not_null
          - name: job_level
            tests:
              - accepted_values:
                  values: ['Intern', 'Fresher', 'Junior', 'Middle', 'Senior', 'Manager', 'Director', 'Unknown', 'Error']