import streamlit as st
import duckdb
import pandas as pd

# 1. PAGE CONFIGURATION
st.set_page_config(page_title="IT Job Market Tracker", layout="wide", page_icon="🚀")
st.title("📊 IT Job Market Dashboard (Real-time)")
st.markdown("Data is automatically extracted and standardized by **LLM (GPT-4o-mini)**.")

# 2. CONNECT TO DATA WAREHOUSE (DUCKDB)
# Use read_only=True to prevent database locking if background crawler scripts are running
conn = duckdb.connect('job_market.duckdb', read_only=True)

try:
    # 3. FETCH DATA FROM GOLD LAYER
    st.subheader("🔥 Top In-Demand Tech Skills")
    
    # Query directly from the View generated by dbt
    df_skills = conn.execute("""
        SELECT skill, total_mentions 
        FROM gold_top_skills 
        LIMIT 15
    """).df()

    # 4. RENDER VISUALIZATIONS
    if not df_skills.empty:
        # Render a quick, responsive bar chart natively in Streamlit
        st.bar_chart(
            data=df_skills.set_index('skill'), 
            y='total_mentions',
            color="#ff4b4b" # Vibrant red color for visual impact
        )
        
        # Provide an expander to view the raw metrics table
        with st.expander("View Detailed Data Table"):
            st.dataframe(df_skills, use_container_width=True)
    else:
        st.warning("No data found in the Gold Layer. Please ensure 'silver_itviec_jobs' has data and you have executed 'dbt run'.")

except Exception as e:
    st.error(f"Database query error: {e}")

finally:
    # Always ensure the connection is closed
    conn.close()